---
- name: Install and configure apache
  hosts: webservers
  remote_user: ansible

  tasks:
    - name: Install apache
      yum: 
        name: httpd
        state: latest
    - name: Run apache service
      service:
        name: httpd
        enabled: true
        state: started
    - name: Open http port
      firewalld:
        service: http
        permanent: yes
        state: enabled
    - name: Restart firewalld service
      service:
        name: firewalld
        state: restarted
    - name: Create index.html file
      copy:
        content: 'Welcome to my web server'
        dest: /var/www/html/index.html
        mode: '0644'
...
