---
- name: Configure grub
  hosts: webservers
  remote_user: ansible

  tasks:
    - name: Changing grub options in file
      lineinfile:
        dest: /etc/default/grub
        state: present
        backrefs: yes
        regexp: '^(GRUB_CMDLINE_LINUX=(?!.* biosdevname)\"[^\"]+)(\")'
        line: '\1 net.ifnames=0 biosdevname=0\2'
    - name: Write grub configuration file
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
...
